[project]
name = "cloud-ing5"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Oumar26", email = "113768204+Oumar26@users.noreply.github.com" }
]
requires-python = ">=3.13"
dependencies = []

[project.scripts]
cloud-ing5 = "cloud_ing5:main"

[build-system]
requires = ["uv_build>=0.9.11,<0.10.0"]
build-backend = "uv_build"
